<?xml version="1.0" encoding="utf-8" standalone="no"?>
<xs:schema elementFormDefault="qualified" attributeFormDefault="unqualified" xmlns:sit="http://datex2.eu/schema/3/situation" version="3.7" targetNamespace="http://datex2.eu/schema/3/situation" xmlns:com="http://datex2.eu/schema/3/common" xmlns:loc="http://datex2.eu/schema/3/locationReferencing" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:import namespace="http://datex2.eu/schema/3/locationReferencing" schemaLocation="DATEXII_3_LocationReferencing.xsd" />
  <xs:import namespace="http://datex2.eu/schema/3/common" schemaLocation="DATEXII_3_Common.xsd" />
  <xs:complexType name="_CommentTypeEnum">
    <xs:simpleContent>
      <xs:extension base="sit:CommentTypeEnum">
        <xs:attribute name="_extendedValue" type="sit:_CommentTypeEnumExtensionType" />
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:simpleType name="_CommentTypeEnumExtensionType">
    <xs:restriction base="xs:string" />
  </xs:simpleType>
  <xs:complexType name="_PoorEnvironmentTypeEnum">
    <xs:simpleContent>
      <xs:extension base="sit:PoorEnvironmentTypeEnum">
        <xs:attribute name="_extendedValue" type="xs:string" />
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="_ProbabilityOfOccurrenceEnum">
    <xs:simpleContent>
      <xs:extension base="sit:ProbabilityOfOccurrenceEnum">
        <xs:attribute name="_extendedValue" type="xs:string" />
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="_SeverityEnum">
    <xs:simpleContent>
      <xs:extension base="sit:SeverityEnum">
        <xs:attribute name="_extendedValue" type="xs:string" />
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="Comment">
    <xs:annotation>
      <xs:documentation>A free text comment with an optional date/time stamp that can be used by the operator to convey additional observations/information that are not possible to code otherwise.</xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element name="comment" type="com:MultilingualString" minOccurs="1" maxOccurs="1">
        <xs:annotation>
          <xs:documentation>A free text comment that can be used by the operator to convey un-coded observations/information.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="commentDateTime" type="com:DateTime" minOccurs="0" maxOccurs="1">
        <xs:annotation>
          <xs:documentation>The date/time at which the comment was made.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="commentType" type="sit:_CommentTypeEnum" minOccurs="0" maxOccurs="1">
        <xs:annotation>
          <xs:documentation>A classification of the the type of comment.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="_commentExtension" type="com:_ExtensionType" minOccurs="0" />
    </xs:sequence>
  </xs:complexType>
  <xs:simpleType name="CommentTypeEnum">
    <xs:annotation>
      <xs:documentation>Classification of comment types.</xs:documentation>
    </xs:annotation>
    <xs:restriction base="xs:string">
      <xs:enumeration value="description">
        <xs:annotation>
          <xs:documentation>A free text human oriented description of the situation element defined by the SituationRecord.</xs:documentation>
        </xs:annotation>
      </xs:enumeration>
      <xs:enumeration value="_extended" />
    </xs:restriction>
  </xs:simpleType>
  <xs:complexType name="Conditions">
    <xs:annotation>
      <xs:documentation>Any conditions which have the potential to degrade normal driving conditions.</xs:documentation>
    </xs:annotation>
    <xs:complexContent>
      <xs:extension base="sit:TrafficElement">
        <xs:sequence>
          <xs:element name="_conditionsExtension" type="com:_ExtensionType" minOccurs="0" />
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="PoorEnvironmentConditions">
    <xs:annotation>
      <xs:documentation>Any environmental conditions which may be affecting the driving conditions on the road.</xs:documentation>
    </xs:annotation>
    <xs:complexContent>
      <xs:extension base="sit:Conditions">
        <xs:sequence>
          <xs:element name="poorEnvironmentType" type="sit:_PoorEnvironmentTypeEnum" minOccurs="1" maxOccurs="unbounded">
            <xs:annotation>
              <xs:documentation>The type of environment condition which is affecting driving conditions.</xs:documentation>
            </xs:annotation>
          </xs:element>
          <xs:element name="precipitationDetail" type="com:PrecipitationDetail" minOccurs="0" />
          <xs:element name="visibility" type="com:Visibility" minOccurs="0" />
          <xs:element name="temperature" type="com:Temperature" minOccurs="0" />
          <xs:element name="wind" type="com:Wind" minOccurs="0" />
          <xs:element name="humidity" type="com:Humidity" minOccurs="0" />
          <xs:element name="_poorEnvironmentConditionsExtension" type="com:_ExtensionType" minOccurs="0" />
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:simpleType name="PoorEnvironmentTypeEnum">
    <xs:annotation>
      <xs:documentation>Types of poor environmental conditions.</xs:documentation>
    </xs:annotation>
    <xs:restriction base="xs:string">
      <xs:enumeration value="denseFog">
        <xs:annotation>
          <xs:documentation>Dense fog, limiting visibility to 50m or less.</xs:documentation>
        </xs:annotation>
      </xs:enumeration>
      <xs:enumeration value="fog">
        <xs:annotation>
          <xs:documentation>Fog, visibility more than 50m.</xs:documentation>
        </xs:annotation>
      </xs:enumeration>
      <xs:enumeration value="freezingFog">
        <xs:annotation>
          <xs:documentation>Fog, in conjunction with sub-zero air temperatures causing possible freezing of road surface.</xs:documentation>
        </xs:annotation>
      </xs:enumeration>
      <xs:enumeration value="gustyWinds">
        <xs:annotation>
          <xs:documentation>Constantly varying winds, significant at times.</xs:documentation>
        </xs:annotation>
      </xs:enumeration>
      <xs:enumeration value="heavyRain">
        <xs:annotation>
          <xs:documentation>Heavy rainfall, limiting visibility to 50m or less.</xs:documentation>
        </xs:annotation>
      </xs:enumeration>
      <xs:enumeration value="heavySnowfall">
        <xs:annotation>
          <xs:documentation>Dense falling snow, limiting visibility to 50m or less.</xs:documentation>
        </xs:annotation>
      </xs:enumeration>
      <xs:enumeration value="patchyFog">
        <xs:annotation>
          <xs:documentation>Fog, in which intermittent areas of dense fog may be encountered.</xs:documentation>
        </xs:annotation>
      </xs:enumeration>
      <xs:enumeration value="rain">
        <xs:annotation>
          <xs:documentation>Rain, visibility more than 50m.</xs:documentation>
        </xs:annotation>
      </xs:enumeration>
      <xs:enumeration value="showers">
        <xs:annotation>
          <xs:documentation>Light rain or intermittent rain.</xs:documentation>
        </xs:annotation>
      </xs:enumeration>
      <xs:enumeration value="sleet">
        <xs:annotation>
          <xs:documentation>Rain mingled with snow or hail.</xs:documentation>
        </xs:annotation>
      </xs:enumeration>
      <xs:enumeration value="snowfall">
        <xs:annotation>
          <xs:documentation>Falling snow, visibility more than 50m.</xs:documentation>
        </xs:annotation>
      </xs:enumeration>
      <xs:enumeration value="stormForceWinds">
        <xs:annotation>
          <xs:documentation>Winds between 90 km/h and 120 km/h.</xs:documentation>
        </xs:annotation>
      </xs:enumeration>
      <xs:enumeration value="strongWinds">
        <xs:annotation>
          <xs:documentation>Winds between 40 km/h and 60 km/h.</xs:documentation>
        </xs:annotation>
      </xs:enumeration>
      <xs:enumeration value="visibilityReduced">
        <xs:annotation>
          <xs:documentation>Environmental conditions causing reduced visibility.</xs:documentation>
        </xs:annotation>
      </xs:enumeration>
      <xs:enumeration value="_extended" />
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="ProbabilityOfOccurrenceEnum">
    <xs:annotation>
      <xs:documentation>Levels of confidence that the sender has in the information, ordered {certain, probable, risk of}.</xs:documentation>
    </xs:annotation>
    <xs:restriction base="xs:string">
      <xs:enumeration value="certain">
        <xs:annotation>
          <xs:documentation>The source is completely certain of the occurrence of the situation record version content.</xs:documentation>
        </xs:annotation>
      </xs:enumeration>
      <xs:enumeration value="riskOf">
        <xs:annotation>
          <xs:documentation>The source has a moderate level of confidence of the occurrence of the situation record version content.</xs:documentation>
        </xs:annotation>
      </xs:enumeration>
      <xs:enumeration value="_extended" />
    </xs:restriction>
  </xs:simpleType>
  <xs:complexType name="RoadSurfaceConditions" abstract="true">
    <xs:annotation>
      <xs:documentation>Conditions of the road surface which may affect driving conditions. These may be related to the weather (e.g. ice, snow etc.) or to other conditions (e.g. oil, mud, leaves etc. on the road)</xs:documentation>
    </xs:annotation>
    <xs:complexContent>
      <xs:extension base="sit:Conditions">
        <xs:sequence>
          <xs:element name="_roadSurfaceConditionsExtension" type="com:_ExtensionType" minOccurs="0" />
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:simpleType name="SeverityEnum">
    <xs:annotation>
      <xs:documentation>Levels of severity of a situation as whole assessed by the impact that the situation may have on traffic flow as perceived by the supplier.</xs:documentation>
    </xs:annotation>
    <xs:restriction base="xs:string">
      <xs:enumeration value="high">
        <xs:annotation>
          <xs:documentation>Perceived by supplier as being of a high level.</xs:documentation>
        </xs:annotation>
      </xs:enumeration>
      <xs:enumeration value="medium">
        <xs:annotation>
          <xs:documentation>Perceived by supplier as being of a medium level.</xs:documentation>
        </xs:annotation>
      </xs:enumeration>
      <xs:enumeration value="low">
        <xs:annotation>
          <xs:documentation>Perceived by supplier as being of a low level.</xs:documentation>
        </xs:annotation>
      </xs:enumeration>
      <xs:enumeration value="_extended" />
    </xs:restriction>
  </xs:simpleType>
  <xs:complexType name="Situation">
    <xs:annotation>
      <xs:documentation>An identifiable instance of a traffic/travel situation comprising one or more traffic/travel circumstances which are linked by one or more causal relationships. Each traffic/travel circumstance is represented by a Situation Record.</xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element name="overallSeverity" type="sit:_SeverityEnum" minOccurs="0" maxOccurs="1">
        <xs:annotation>
          <xs:documentation>The overall assessment of the impact (in terms of severity) that the situation as a whole is having, or will have, on the traffic flow as perceived by the supplier.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="situationVersionTime" type="com:DateTime" minOccurs="0" maxOccurs="1">
        <xs:annotation>
          <xs:documentation>The date/time that this current version of the Situation was written into the database of the supplier which is involved in the data exchange. Identity and version of the situation are defined by the class stereotype implementation.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="headerInformation" type="com:HeaderInformation" />
      <xs:element name="situationRecord" type="sit:SituationRecord" maxOccurs="unbounded">
        <xs:annotation>
          <xs:documentation>Details of the Situation</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="_situationExtension" type="com:_ExtensionType" minOccurs="0" />
    </xs:sequence>
    <xs:attribute name="id" type="xs:string" use="required" />
  </xs:complexType>
  <xs:complexType name="SituationPublication">
    <xs:annotation>
      <xs:documentation>A publication containing zero or more traffic/travel situations.</xs:documentation>
    </xs:annotation>
    <xs:complexContent>
      <xs:extension base="com:PayloadPublication">
        <xs:sequence>
          <xs:element name="situation" type="sit:Situation" minOccurs="0" maxOccurs="unbounded" />
          <xs:element name="_situationPublicationExtension" type="com:_ExtensionType" minOccurs="0" />
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="SituationRecord" abstract="true">
    <xs:annotation>
      <xs:documentation>An identifiable versioned instance of a single record/element within a situation.</xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element name="situationRecordCreationTime" type="com:DateTime" minOccurs="1" maxOccurs="1">
        <xs:annotation>
          <xs:documentation>The date/time that the SituationRecord object (the first version of the record) was created by the original supplier.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="situationRecordVersionTime" type="com:DateTime" minOccurs="1" maxOccurs="1">
        <xs:annotation>
          <xs:documentation>The date/time that this current version of the SituationRecord within the situation was written into the database of the supplier which is involved in the data exchange. Identity and version of record are defined by the class stereotype implementation.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="probabilityOfOccurrence" type="sit:_ProbabilityOfOccurrenceEnum" minOccurs="1" maxOccurs="1">
        <xs:annotation>
          <xs:documentation>An assessment of the degree of likelihood that the reported event will occur.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="safetyRelatedMessage" type="com:Boolean" minOccurs="0" maxOccurs="1">
        <xs:annotation>
          <xs:documentation>Indicates whether this SituationRecord specifies a safety-related traffic situation. At least all traffic situations governed by Commission Delegated Regulation (EU) No 886/2013 shall be indicated.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="source" type="com:Source" minOccurs="0" />
      <xs:element name="validity" type="com:Validity" />
      <xs:element name="generalPublicComment" type="sit:Comment" minOccurs="0" maxOccurs="unbounded">
        <xs:annotation>
          <xs:documentation>A comment which may be freely distributed to the general public</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="locationReference" type="loc:LocationReference" />
      <xs:element name="_situationRecordExtension" type="com:_ExtensionType" minOccurs="0" />
    </xs:sequence>
    <xs:attribute name="id" type="xs:string" use="required" />
    <xs:attribute name="version" type="xs:string" use="required" />
  </xs:complexType>
  <xs:complexType name="TrafficElement" abstract="true">
    <xs:annotation>
      <xs:documentation>An event which is not planned by the traffic operator, which is affecting, or has the potential to affect traffic flow.</xs:documentation>
    </xs:annotation>
    <xs:complexContent>
      <xs:extension base="sit:SituationRecord">
        <xs:sequence>
          <xs:element name="_trafficElementExtension" type="com:_ExtensionType" minOccurs="0" />
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="WeatherRelatedRoadConditions">
    <xs:annotation>
      <xs:documentation>Road surface conditions that are related to the weather which may affect the driving conditions, such as ice, snow or water.</xs:documentation>
    </xs:annotation>
    <xs:complexContent>
      <xs:extension base="sit:RoadSurfaceConditions">
        <xs:sequence>
          <xs:element name="weatherRelatedRoadConditionType" type="com:_WeatherRelatedRoadConditionTypeEnum" minOccurs="1" maxOccurs="unbounded">
            <xs:annotation>
              <xs:documentation>The type of road surface condition that is related to the weather which is affecting the driving conditions.</xs:documentation>
            </xs:annotation>
          </xs:element>
          <xs:element name="_weatherRelatedRoadConditionsExtension" type="com:_ExtensionType" minOccurs="0" />
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
</xs:schema>